#!/bin/bash
#set -xv
source debug_config
source default_repo

if [ -f "/etc/mix/mix.conf" ];then
    source "/etc/mix/mix.conf"
fi
if [ -f "/etc/mix/repos.conf" ];then
    source "/etc/mix/repos.conf"
fi

if [ -z "$1" ];then
	echo "Unknown operation. Type '$0 help' to get help."
	exit 1
fi
if [[ -z "$2" ]];then
	if [[ "$1" != "help" ]];then
		echo "No package to operate on!"
		exit 1
	fi
fi

# Settings from "mix.conf"
# Some basic directories
if [ -z "$ROOT" ];then
	export ROOT="/"
fi
if [ -z "$USR" ];then
	export USR="$ROOT/usr"
fi
if [ -z "$VAR" ];then
	export VAR="$ROOT/var"
fi
# This is where repositories are being saved locally
if [ -z "$LOCAL_REPO" ];then
	export PKG="$VAR/cache/mix/local_repo"
fi
# This is where system status is saved
if [ -z "$STATUS" ];then
	export DATA="$VAR/cache/mix/status"
fi

# Define colors
WHI="\e[1;37m"
RED="\e[1;31m"
GRN="\e[1;32m"
YLW="\e[1;33m"
BLU="\e[1;34m"
NC="\e[0m"

# Create some required files for mixture if they don't exist yet
if [[ ! -f "$STATUS"/installed-list ]]; then
	ad -i -p "$LI"
	af "$LI/installed-list"
fi
if [[ ! -f "$STATUS"/installed-manually-list ]]; then
	ad -i -p "$LI"
	af "$LI/installed-manually-list"
fi
if [[ "$ROOT" != /* || "$USR" != /* || "$VAR" != /* || "$LOCAL_REPO" != /* || "$STATUS" != /* ]];then
	echo "Non-absolute paths found in configuration!"
	exit 1
fi

ad -i "$ROOT" "$USR" "$VAR" "$SRC" "$LOCAL_REPO" "$STATUS"

CHECKERR() {
	if [[ $1 != 0 ]]
	then
		echo -en "${RED}Installation unexpectedly failed!${NC}\nReport this issue to the package maintainer!\n"
		exit 1
	fi
}

if [[ "$1" == "install" ]]; then
	# Check existance of all packages requested by user
	for PKG in "${@:2}"; do
		echo "- Checking existence: $PKG"
		if [[ ! -d "$LOCAL_REPO/$PKG" ]];then
			echo "$PKG: Package could not be found!"
			exit 1
		fi
	done
	# Check dependencies
	for PKG in "${@:2}"; do
		echo "- Checking dependencies: $PKG"
		source "$LOCAL_REPO/$PKG/mixture"
		for DEP in ${RUNTIME_DEPS} ; do
			echo "NOTICE: Package $PKG depends on $DEP"
		done
	done
	echo "Abort!"			
	exit 0

	echo "- Cheking intergrity..."
	cd "$PKG" || exit 1
	sha512sum -c "$2".mix.sha512 --status
	CHECKERR $?
	echo "- Unpacking .mix package..."
	ad -p "$MIXPKG"
	tar -xhf "$PKG/$2.mix" -C "$MIXPKG"
	chckerr
	cd "$MIXPKG" || exit 1
	echo "- Checking file collisions..."
	# Check if package already exists
	source "./metadata.mixdata"
	if grep "$2:$VERSION" "$LI/installed-list" -xq; then
		echo "This package is already installed!"
		exit 1
	fi
	# Check if file collides with another file from another package
	while read -r f; do
		e=0
		if [ -f "$ROOT/$f" ];then
			while read -r p;do
				pkg="$(echo "$p" | awk -F':' '{ print $1 }')"
				if [[ "$pkg" != "$2" ]]; then
					while read -r f;do
						filename="$(echo "$f" | awk -F'  ' '{ print $2 }')"
						echo "File $ROOT/$filename is already reserved by a package \"$pkg\""
						e=1
					done < "$DATA"/"$2"/filelist.mixdata
				fi
			done < "$LI"/installed-list
		fi
		if [[ "$e" != 0 ]];then
			exit 1
elif [[ "$1" == "remove" ]]; then
	echo -e ">> TODO!"
elif [[ "$1" == "update" ]]; then
	echo -e ">> TODO!"
elif [[ "$1" == "search" ]]; then
	echo -e ">> TODO!"
elif [[ "$1" == "sync" ]]; then
	echo -e ">> TODO!"
elif [[ "$1" == "help" ]];then
echo -ne "MIXTURE - A package builder and deployer for the Carrot system

It supports the following operations:
install        Add a feature to system
remove         Remove a feature from system
update         Update all or some packages
search         Find a package in repositories
sync           Syncronize software repositories
"
else
		echo "Unknown operation. Type '$0 help' to get help."
		exit 1
fi
