#!/bin/bash
#set -xv
source default_config
if [ -f "/etc/mixture.conf" ];then
    source "/etc/mixture.conf"
fi
if [ -z "$1" ];then
	echo "Unknown operation. Type '$0 help' to get help."
	exit 1
fi
if [[ -z "$2" ]];then
	if [[ "$1" != "help" && "$1" != "check" && "$1" != "list-installed" && "$1" != "list-cached" && "$1" != "list-manual" ]];then
		echo "No package to operate on!"
		exit 1
	fi
fi
# Filesystem where all packages will be installed
if [ -z "$ROOT" ];then
	export ROOT="/"
fi
# /usr directory of this filesystem
if [ -z "$USR" ];then
	export USR="$ROOT/usr"
fi
# /var directory of this filesystem
if [ -z "$VAR" ];then
	export VAR="$ROOT/var"
fi
# Metadata with source tarballs
# This is also a directory where packages will be built
if [ -z "$SRC" ];then
	export SRC="$USR/src/mixtures"
fi
# Metadata of installed packages
if [ -z "$DATA" ];then
	export DATA="$VAR/cache/mix/data"
fi
# Tarballs with available packages, ready for installation
if [ -z "$PKG" ];then
	export PKG="$VAR/cache/mix/pkgs"
fi
# Custom files for MIX
if [ -z "$LI" ];then
	export LI="$VAR/cache/mix/localindex"
fi

# Create some required files for mixture if they don't exist yet
if [[ ! -f "$LI"/installed-list ]]; then
	ad "$LI"
	af "$LI/installed-list"
fi
if [[ "$ROOT" != /* || "$USR" != /* || "$VAR" != /* || "$SRC" != /* || "$DATA" != /* || "$PKG" != /* || "$LI" != /* ]];then
	echo "Non-absolute paths found in configuration!"
	exit 1
fi

ad "$ROOT" "$USR" "$VAR" "$SRC" "$PKG" "$LI" &> /dev/null

# Define colors
WHI="\e[1;37m"
RED="\e[1;31m"
GRN="\e[1;32m"
YLW="\e[1;33m"
BLU="\e[1;34m"
NC="\e[0m"

chckerr() {
	if [[ "$?" != 0 ]]
	then
		echo -en "Failed to build a package. \nPlease, see the log file: $MIXBLD/building.log\n"
		exit 1
	fi
}

echo -e "${GRN}>>> ${WHI}$2${NC}"
if [[ "$1" == "compile" ]]; then
		if [[ ! -d "$SRC/$2" ]];then
			echo "Package with supplied name cannot be found!"
			exit 1
		else
			export MIXBLD="$SRC/$2"
			export MIXPKG="$PKG/$2.mix"
			export MIXDATA="$DATA/$2/"
		fi
		echo -e "${WHI}- BUILDING ${NC}"
		echo -e "  Build directory:    $MIXBLD"
		echo -e "  Ready package path: $MIXPKG"
		echo -e "  Metadata directory: $MIXDATA"
		echo -e ""
		if [[ -f "$MIXBLD/building.log" ]];then rf "$MIXBLD/building.log"; fi
		ad "$MIXBLD"
		af "$MIXBLD/building.log"
		cd "$MIXBLD" || exit 1
		if [[ -f "$MIXBLD/fs" ]];then rd -r "$MIXBLD/fs"; fi
		if [[ -f "$MIXBLD/unpacked" ]];then rd -r "$MIXBLD/unpacked"; fi
		if [[ -f "$MIXBLD/$2.mix" ]];then rf "$MIXBLD/$2.mix"; fi
		if [[ -f "$MIXBLD/files.mixdata" ]];then rf "$MIXBLD/files.mixdata"; fi
		echo -e "  Sourcing the mixture file..." | tee -a "$MIXBLD/building.log"
		source "$MIXBLD/magician" "none"
		echo -e "  Downloading sources..." | tee -a "$MIXBLD/building.log"
		index=1
		for res in "${DOWNLOAD[@]}"; do
			curl -C - $res -Lo $index-$NAME-$VERSION
			#wget -c "$res" -O "$index-$NAME-$VERSION"
			chckerr
			index=$((++index))
		done
		echo -e "  Unpacking sources..." | tee -a "$MIXBLD/building.log"
		ad "unpacked"
		index=1
		continueloop=true
		while [[ $continueloop == true ]];do
			if [[ -f $index-$NAME-$VERSION ]]; then
				tar -xhf "$index-$NAME-$VERSION" -C "unpacked" | tee -a "$MIXBLD/building.log"
				chckerr
			else
				continueloop=false
			fi
			index=$((++index))
		done
		echo -e "  Configuring sources..." | tee -a "$MIXBLD/building.log"
		bash "$MIXBLD"/magician conf &>> "$MIXBLD/building.log"
		chckerr
		echo -e "  Compiling sources..." | tee -a "$MIXBLD/building.log"
		PROC="$(nproc)" bash "$MIXBLD"/magician comp &>> "$MIXBLD/building.log"
		chckerr
		echo -e "  Installing sources into temproot..." | tee -a "$MIXBLD/building.log"
		INSTALLTO="$MIXBLD/fs/" bash "$MIXBLD"/magician setup &>> "$MIXBLD/building.log"
		chckerr
elif [[ "$1" == "package" ]]; then
		if [[ ! -d "$SRC/$2" ]];then
			echo "Package with supplied name cannot be found!"
			exit 1
		else
			export MIXBLD="$SRC/$2"
			export MIXPKG="$PKG/$2.mix"
			export MIXDATA="$DATA/$2/"
		fi
		echo -e "${WHI}- PACKAGING ${NC}"
		echo -e "  Build directory:    $MIXBLD"
		echo -e "  Ready package path: $MIXPKG"
		echo -e "  Metadata directory: $MIXDATA"
		echo -e ""
		echo -e "  Sourcing the mixture file..." | tee -a "$MIXBLD/building.log"
		cd "$MIXBLD"
		source "$MIXBLD/magician" "none"
		echo -e "  Making a tarball..." | tee -a "$MIXBLD/building.log"
		ad "$MIXDATA"
		cd "$MIXBLD/fs/" || exit 1
		tar -cJf "$MIXBLD/$2.mix" "."
		chckerr
		cd "$MIXBLD/fs/" || exit 1
		filelist=$(tar -Jtf "$MIXBLD/$2.mix" | tail -n +2)
		for file in $filelist ;do 
			if [[ ! -d "$file" ]];then
				echo "$(sha512sum "$file")" >> "$MIXBLD/files.mixdata"
			fi
		done
		chckerr
		cd "$MIXBLD" || exit 1
		c -o "$MIXBLD/$2.mix" "$MIXPKG"
		chckerr
		c -o "$MIXBLD/files.mixdata" "$MIXDATA"
		chckerr
		c -o "$MIXBLD/metadata.mixdata" "$MIXDATA"
		chckerr
		# c -o "$MIXBLD/building.log" "$MIXPKG/building.log"
		c -o "$MIXBLD/deps.mixdata" "$MIXDATA"
		chckerr
		echo -e "  Cleaning up..." | tee -a "$MIXBLD/building.log"
		rf "$MIXBLD/$2.mix"
		rf "$MIXBLD/files.mixdata"
		rf "$MIXBLD/"*-$NAME-$VERSION
		rd -r "$MIXBLD/unpacked"
		rd -r "$MIXBLD/fs"
		rf "$MIXBLD/building.log"
elif [[ "$1" == "deploy" ]];then
		export MIXBLD="$SRC/$2"
		export MIXPKG="$PKG/$2.mix"
		export MIXDATA="$DATA/$2/"
		if [[ ! -f "$MIXPKG" ]];then
			echo "Package with supplied name cannot be found!"
			exit 1
		fi
		echo -e "${WHI}- DEPLOYING ${NC}"
		echo -e "  Build directory:    $MIXBLD"
		echo -e "  Ready package path: $MIXPKG"
		echo -e "  Metadata directory: $MIXDATA"
		echo -e ""
		echo "  Checking file collisions..."
		# Check if package already exists
		source "$MIXDATA/metadata.mixdata"
		if grep "$2:$VERSION" "$LI/installed-list" -xq; then
			echo "This package is already installed!"
			exit 1
		fi
		# Check if file collides with another file from another package
		while read -r f; do
			e=0
			if [ -f "$ROOT/$f" ];then
				while read -r p;do
					pkg="$(echo "$p" | awk -F':' '{ print $1 }')"
					if [[ "$pkg" != "$2" ]]; then
						while read -r f;do
							filename="$(echo "$f" | awk -F'  ' '{ print $2 }')"
							echo "File $ROOT/$filename is already reserved by a package \"$pkg\""
							e=1
						done < "$DATA"/"$pkg"/files.mixdata
					fi
				done < "$LI"/installed-list
			fi
			if [[ "$e" != 0 ]];then
				exit 1
			fi
		done < "$MIXDATA"/files.mixdata
		echo -e "  Extracting files..."
		tar -xhJf "$MIXPKG" -C "$ROOT"
		chckerr
		echo -e "  Diagnosing..."
		while read -r f;do
			for file in $(echo "$f" | awk -F'  ' '{ print $2 }'); do
				if [[ ! -e "$ROOT/$file" ]];then
					echo "File is missing: $ROOT/$file"
				fi
			done
		done < "$MIXDATA"/files.mixdata
		echo "$2:$VERSION" >> "$LI/installed-list"
		# MIXTURE nie powinien tego robić
		#if [[ "$(echo "$@" | grep -w "$2")" ]];then
		#	echo "$2:$VERSION" >> "$LI/manually-installed-list"
		#fi
elif [[ "$1" == "remove" ]];then
		if "$0" check "$2" &> /dev/null ;then
			export MIXBLD="$SRC/$2"
			export MIXPKG="$PKG/$2.mix"
			export MIXDATA="$DATA/$2/"
		else
			echo "Package with supplied name cannot be found!"
			exit 1
		fi
		echo -e "${WHI}- REMOVING ${NC}"
		echo -e "  Removing all files..."
		while read -r f;do
			for file in $(echo "$f" | awk -F'  ' '{ print $2 }'); do
				file=$(echo "$f" | awk -F'  ' '{ print $2 }')
				if [[ -f "$ROOT/$file" || -h "$ROOT/$file" ]];then
					rf "$ROOT/$file"
				elif [[ -d "$ROOT/$file" ]];then
					rd "$ROOT/$file"
				else
					echo "Refusing to remove non-empty directory: $ROOT/$file"
				fi
				chckerr
			done
		done < "$MIXDATA"/files.mixdata
		chckerr
		sed "/$2/d" -i "$LI/installed-list"
		sed "/$2/d" -i "$LI/manually-installed-list"
elif [[ "$1" == "check" ]];then
		if p "$LI/installed-list" | awk -F':' '{ print $1 }' |  grep -w "$2" ;then
			echo -e "OK"
			exit 0
		else
			echo -e "NOTOK"
			exit 1
		fi
elif [[ "$1" == "files" ]];then
		if [[ ! "$("$0" check "$2")" ]];then
			echo "Package with supplied name could not be found!"
			exit 1
		else
			export MIXBLD="$SRC/$2"
			export MIXPKG="$PKG/$2.mix"
			export MIXDATA="$DATA/$2/"
		fi
		tar -Jtf "$MIXPKG"
elif [[ "$1" == "list-installed" ]];then
		if [[ -n "$2" && "$(p "$LI"/installed-list | grep -x "$2")" ]] ; then
			echo "OK"
			exit 0
		elif [[ -n "$2" && ! "$(p "$LI"/installed-list | grep -x "$2")" ]] ; then
			echo "FALSE"
			exit 1
		else
			p "$LI/installed-list"
		fi
elif [[ "$1" == "list-manual" ]];then
		if [[ -n "$2" && "$(p "$LI"/manually-installed-list | grep -x "$2")" ]] ; then
			echo "OK"
			exit 0
		elif [[ -n "$2" && ! "$(p "$LI"/manually-installed-list | grep -x "$2")" ]] ; then
			echo "FALSE"
			exit 1
		else
			p "$LI/installed-list"
		fi
elif [[ "$1" == "list-cached" ]];then
		l "$PKG"
elif [[ "$1" == "help" ]];then
echo -ne "MIXTURE - A package builder and deployer for the Carrot system

It supports the following operations:
compile        Build a package into specified directory
package        Create a \".mix\" file from specified directory
deploy         Install a package from tarball
remove         Uninstall a package from system
list-installed List installed packages
list-manual    List manually installed packages
list-cached    List downloaded packages that are ready to install
check          Verify if specified package is installed
"
else
		echo "Unknown operation. Type '$0 help' to get help."
		exit 1
fi
